defaults:
  - eval_vggt_eth3d_local.yaml
  - _self_


model:
  patch_module:
    type: query_topk_keys
    keep_ratio: 0.2
    layer_start: 0
    layer_end: 10
    query_chunk_size: 128

datasets:
  eth3d:
    eval_tasks: [pose, recon_unposed]
